name: flutter_bluetooth
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  get: ^4.6.1
  permission_handler: ^10.0.0
  logger: ^1.1.0
  collection: ^1.15.0
  syncfusion_flutter_charts: ^27.1.50
  fl_chart: ^0.69.0
  vector_math: ^2.1.4
  intl: ^0.19.0
  dbscan: ^0.1.1
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

# Add this section to allow mixed mode compilation
dependency_overrides:
  dbscan:
    ^0.1.1